### ISSUE TITLE
Possibly of interest: C++ and PostgreSQL-native BK tree implementations.

### ISSUE THREAD

**Issue by fake-name** [deveyNull/phistOfFury#3]
Hey, it's not an issue, but there wasn't another venue.

I've implemented a relatively performant C++ [python-module BK-tree](https://github.com/fake-name/IntraArchiveDeduplicator/tree/master/deduplicator) for exactly this use. I'm also working on implemeing a [BK-tree implementation as a](https://github.com/fake-name/pg-spgist_hamming) PostgreSQL [SP-GiST](https://www.postgresql.org/docs/current/static/spgist.html) custom index operator.

I use the python BK-Tree for performant searching across a ~32M image corpus for a image deduplication project of mine, and it's been quite stable for the last year or so. Currently, a search within an edit distance of 4 takes < 50 milliseconds, and generally touches ~0.5% of the tree. Additionally, since searches are read-only, they scale *very* well with multiple concurrent readers.

Given that, I think the assertion that such tree structures "will get ugly real fast" is probably not correct.

I'm not sure if any of this is interesting, but it might be a convenient source of a [very well tested](https://github.com/fake-name/IntraArchiveDeduplicator/tree/master/Tests) BK-tree implementation.

Another person has spun the BK-tree implementation out into a `pip`able module [here](https://github.com/gpip/cBKTree).

**Comment by deveyNull** [comment]
Didn't think of a bk tree, that's really good. Won't even categorize that as academic shenaniganery because that's so clean. I mostly made that "ugly" comment because I like ragging on photoDNA's design choices... A distance of 4 is good (what length hash?), but the main thing I like about my version is you can have a pretty massive distance and still get the same speed lookup for a "match". I haven't touched this in years, so don't quote me on it, but I had a hardcoded max distance of 15 or so and it still would work with minimal FP. As with everything, it's all about what the use case is. 

As for that ugly pickled write (ugh), I never pushed the code with the persistent db for real time queries for reasons unknown to 2 years later me. 

If I can find it Ill put the faux whitepaper on Github to explain the hacky bs that makes the db do magic.

**Comment by fake-name** [comment]
I'm using 64 bit hashes (basically a int64_t in the code). 

It most definitely does fall over pretty horribly with big search distances.

**Comment by deveyNull** [comment]
Mine is 64 too, wound up being the best length for the final check. Db goes 4-16-64. 

Big search distance and big db with instantaneous lookups is what I optimized for, few  use cases want/need that or have man power to look at all the FB. I keep telling myself Ill make this project look as nice as your repo and write the whitepaper, but I burned myself out and now the words perceptual hashing makes me twitch

**Comment by fake-name** [comment]
Yeah, 64 seems to be a reasonable optimum.

I mostly made mine look decent as it was I think the 3rd time I'd redone the implementation, and I knew I was going for "library quality" code. It went python->cython->C++ in terms of the implementation. 

I've only had the motivation to maintain it because I actually use it continuously, as it's part of a larger deduplication system that hooks into a lot of my hobby projects. I actually only got the kick-in-the-ass to revisit the postgresql index versions after I started having OOM issues recently due to ongoing tree-growh, and not having enough RAM for certain tree-rebuild operations under concurrent access.

Anyways, I commented because I figured you might find it interesting more then anything else. I certainly spent a lot of time on research when I was starting out, and I still find looking at other similar implementations interesting.
